version: '3.5'
services:
  laravel-gallery-app:
    build:
      context: '.'
      dockerfile: 'docker/Dockerfile'
      args:
        uid: ${UID}
    container_name: laravel-gallery-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-gallery-app
  gallery-mariadb:
    image: mariadb:10.4.3-bionic
    container_name: gallery-mariadb
    restart: always
    ports:
      - 3080:3306
    volumes:
      - /var/lib/mysql
    networks:
      backend:
        aliases:
          - db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  gallery-pma:
    image: phpmyadmin/phpmyadmin:5
    container_name: gallery-pma
    depends_on:
      - gallery-mariadb
    restart: always
    ports:
      - 3880:80
    networks:
      backend:
        aliases:
          - phpmyadmin
    environment:
      PMA_HOST: gallery-mariadb
      PMA_PORT: 3306
networks:
  backend:
    external: false
    name: backend-network
volumes:
  redis-datas:
    driver: local
